name: autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: "14 15 */5 * *"

jobs:
  autoupdate:
    # Prevent Forks from running this workflow
    if: github.repository == 'pcrbot/HoshinoBot-plugins-index'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.ci/requirement.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run Script
        id: run-script
        run: |
          pip install -r .ci/requirement.txt
          python .ci/update.py
          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
          changed="false"
          else
          changed="true"
          fi
          echo "changed=${changed}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit if changed
        if: steps.run-script.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update plugins"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      changed: ${{ steps.run-script.outputs.changed }}

  plugins-build:
    needs: autoupdate
    if: needs.autoupdate.outputs.changed == 'true'
    uses: ./.github/workflows/plugins-build.yml
    secrets: inherit
